param([Parameter(Mandatory=$true)][string]$ZipPath)
$ErrorActionPreference='Stop'
$ZipPath=[IO.Path]::GetFullPath($ZipPath);if(-not(Test-Path $ZipPath)){throw 'Standalone ZIP missing.'}
$sidecar="$ZipPath.sha256";if(-not(Test-Path $sidecar)){throw 'Standalone SHA-256 sidecar missing.'}
$actual=(Get-FileHash $ZipPath -Algorithm SHA256).Hash.ToLowerInvariant();$expected=((Get-Content $sidecar -Raw).Trim()-split'\s+')[0].ToLowerInvariant();if($actual-ne$expected){throw 'Standalone ZIP SHA-256 mismatch.'}
$package=[IO.Path]::GetFileNameWithoutExtension($ZipPath);$temp=Join-Path ([IO.Path]::GetTempPath()) ('twc-standalone-'+[Guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Path $temp|Out-Null
try{Expand-Archive $ZipPath -DestinationPath $temp; $root=Join-Path $temp $package;$manifest=Get-Content (Join-Path $root 'distribution-manifest.json') -Raw|ConvertFrom-Json -Depth 12;if($manifest.format-ne'TrueWebsiteCloner.StandaloneWindowsDistribution'-or-not$manifest.selfContained-or$manifest.requiresInstalledDotNet){throw 'Standalone manifest policy mismatch.'}
$declared=@{};foreach($record in $manifest.files){$path=[string]$record.path;if($path.Contains('..')-or[IO.Path]::IsPathRooted($path)){throw "Unsafe manifest path: $path"};$file=Join-Path $root $path.Replace('/',[IO.Path]::DirectorySeparatorChar);if(-not(Test-Path $file)){throw "Missing: $path"};if((Get-Item $file).Length-ne[int64]$record.byteLength){throw "Length mismatch: $path"};if((Get-FileHash $file -Algorithm SHA256).Hash.ToLowerInvariant()-ne([string]$record.sha256).ToLowerInvariant()){throw "SHA mismatch: $path"};$declared[$path.ToLowerInvariant()]=$true}
foreach($required in @('bin/desktop/TrueWebsiteCloner.exe','bin/native-host/TrueWebsiteCloner.NativeHost.exe','bin/testlab/TrueWebsiteCloner.TestLab.exe','bin/local-runtime/TrueWebsiteCloner.LocalRuntime.exe','bin/cli/TrueWebsiteCloner.Cli.exe','chrome-extension/manifest.json','Install-TrueWebsiteCloner.ps1','VERSION')){if(-not$declared.ContainsKey($required)){throw "Standalone required file missing: $required"}}
if(Get-ChildItem $root -Recurse -Filter '*.pdb' -File){throw 'Standalone package contains PDB files.'}
$installer=Get-Content (Join-Path $root 'Install-TrueWebsiteCloner.ps1') -Raw;if($installer-match'dotnet --list-runtimes'){throw 'Standalone installer must not require installed dotnet.'};if($installer-notmatch'HKCU:\\Software\\Google\\Chrome\\NativeMessagingHosts'){throw 'HKCU Native Messaging registration missing.'}
Write-Host "PASS  Standalone ZIP SHA-256 $actual" -ForegroundColor Green;Write-Host "PASS  $($manifest.fileCount) file hashes verified";Write-Host 'PASS  no installed .NET runtime prerequisite';Write-Host 'RESULT: V1.0 STANDALONE DISTRIBUTION PASS' -ForegroundColor Green}
finally{try{Remove-Item $temp -Recurse -Force}catch{}}
